# Generated by Django 4.2.13 on 2024-05-28 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0003_remove_student_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="dob",
        ),
    ]
