# Generated by Django 4.2.13 on 2024-05-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0004_remove_student_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("speed", models.IntegerField(default=100)),
            ],
        ),
    ]
