# Generated by Django 4.2.13 on 2024-06-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0003_department_studentid_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_address",
            field=models.TextField(),
        ),
    ]
