# Generated by Django 4.2.13 on 2024-06-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0006_subject_subjectmarks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectmarks",
            options={"ordering": ["student"]},
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateField(auto_created=True)),
                ("student_rank", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentreport",
                        to="vege.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student_rank", "creation_date")},
            },
        ),
    ]
