# Generated by Django 4.2.13 on 2024-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0007_alter_subjectmarks_options_reportcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
