# Generated by Django 4.2.13 on 2024-06-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0008_alter_reportcard_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="creation_date",
            field=models.DateField(auto_now=True),
        ),
    ]
