# Generated by Django 4.2.13 on 2024-06-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0010_alter_reportcard_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentreportcard",
                to="vege.student",
            ),
        ),
    ]
