# Generated by Django 4.2.13 on 2024-06-26 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0011_alter_reportcard_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(
                    2024, 6, 26, 16, 1, 28, 412360, tzinfo=datetime.timezone.utc
                ),
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
