# Generated by Django 4.2.13 on 2024-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0012_recipe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
