# Generated by Django 4.2.13 on 2024-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic2", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_bio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(blank=True, upload_to="profile"),
        ),
    ]
